// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             *string  `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password             *string  `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type RegisterServerRequest struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Type                 *string  `protobuf:"bytes,2,req,name=type" json:"type,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Name                 *string  `protobuf:"bytes,4,req,name=name" json:"name,omitempty"`
	Port                 *int32   `protobuf:"varint,5,req,name=port" json:"port,omitempty"`
	Ip                   *string  `protobuf:"bytes,6,req,name=ip" json:"ip,omitempty"`
	OnLine               *int32   `protobuf:"varint,7,opt,name=onLine" json:"onLine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterServerRequest) Reset()         { *m = RegisterServerRequest{} }
func (m *RegisterServerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterServerRequest) ProtoMessage()    {}
func (*RegisterServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *RegisterServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServerRequest.Unmarshal(m, b)
}
func (m *RegisterServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServerRequest.Merge(m, src)
}
func (m *RegisterServerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterServerRequest.Size(m)
}
func (m *RegisterServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServerRequest proto.InternalMessageInfo

func (m *RegisterServerRequest) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RegisterServerRequest) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *RegisterServerRequest) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *RegisterServerRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RegisterServerRequest) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *RegisterServerRequest) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *RegisterServerRequest) GetOnLine() int32 {
	if m != nil && m.OnLine != nil {
		return *m.OnLine
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*RegisterServerRequest)(nil), "RegisterServerRequest")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xcc, 0x4d, 0xaa, 0x83, 0x40,
	0x10, 0x04, 0x60, 0xfc, 0x7d, 0xcf, 0x8e, 0x84, 0x20, 0x04, 0x7a, 0x29, 0xae, 0x5c, 0x65, 0x91,
	0x73, 0xb8, 0x32, 0x27, 0x10, 0x6c, 0x64, 0x08, 0x99, 0xee, 0xf4, 0x8c, 0x06, 0x6f, 0x1f, 0x66,
	0x82, 0xcb, 0xaa, 0xe2, 0x2b, 0xa8, 0x26, 0x31, 0x37, 0x51, 0xf6, 0xdc, 0xdd, 0xa1, 0x1e, 0x78,
	0x31, 0x76, 0xa4, 0xf7, 0x4a, 0xce, 0x37, 0x17, 0xf8, 0x5f, 0x1d, 0xa9, 0x9d, 0x5e, 0x84, 0x49,
	0x9b, 0xf6, 0x55, 0x68, 0x64, 0x72, 0xee, 0xc3, 0x3a, 0x63, 0x1a, 0x9a, 0x6e, 0x83, 0xeb, 0x48,
	0x8b, 0x71, 0x9e, 0xf4, 0x41, 0xba, 0x91, 0x1e, 0x18, 0x20, 0x35, 0x73, 0x64, 0x45, 0x53, 0x43,
	0xee, 0x77, 0xa1, 0x1f, 0x69, 0x4e, 0x90, 0x3d, 0x69, 0xc7, 0x2c, 0x86, 0x1a, 0xf2, 0xf8, 0x9f,
	0x1f, 0x49, 0x58, 0x3d, 0x16, 0x91, 0x85, 0x0b, 0xc1, 0x32, 0x2e, 0x67, 0x28, 0xd9, 0x0e, 0xc6,
	0x12, 0xfe, 0xb5, 0x49, 0x5f, 0x7c, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x5d, 0xf2, 0xc4, 0xb7,
	0x00, 0x00, 0x00,
}
